server:
  port:8005

spring:
  datasource:
    username: root
    password: jwc
    url: jdbc:mysql://100.85.14.120:3307/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      ribbon:
        enabled: false  # 彻底关闭 Ribbon
  application:
    name: gulimall-ware

feign:
  sentinel:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.com.atguigu.gulimall: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

